version: '3.7'

services:
  keycloak:
    build: .
    container_name: mykeycloak
    ports:
      - "8443:8443"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KC_HOSTNAME=localhost
    volumes:
      - ./realm-config.json:/opt/keycloak/data/import/realm-config.json
    command:
      - start-dev
      - --import-realm
